version: '3.8'

services:
  parties-service:
    container_name: parties-service
    build: ./parties-service
    ports:
     - "8081:8080"

  party-web:
    container_name: party-web
    build: ./web-app
    ports:
     - "8082:8080"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
